### ISSUE TITLE
Sometimes Attaching hci0 doesn't succeed.

### ISSUE THREAD

**Issue by craigmulligan** [resin-io-projects/rpi3-bluetooth#3]
Currently we only try twice. We should instead keep trying until it succeeds. 

Ref: https://forums.resin.io/t/rpi3-bluetooth/780

**Comment by jbaldwinroberts** [comment]
@agherzan any idea why [this](https://github.com/resin-io-projects/rpi3-bluetooth/blob/master/scan.sh#L8) does not work the first time, every time? Why do we try twice?

**Comment by agherzan** [comment]
No idea. I remember though that when i first started to play with it I had to retry as well. Didn't dig to see what's going on.

**Comment by imrehg** [comment]
Closed by retrying ad infinitum, but the underlying issue is not totally clear.
