### ISSUE TITLE
Update example to work with new resinOS versions

### ISSUE THREAD

**Issue by jhermsmeier** [resin-io-projects/rpi3-bluetooth#6]
There has been an updated, but undocumented example for testing Bluetooth at https://github.com/resin-io-playground/test-bluetooth – which this example needs updating with.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_8tq9)

**Comment by floion** [comment]
Not updated but rather the other one is the appropriate one for a smoke test for BT on the rpi3 and rpi zero wireless

**Comment by imrehg** [comment]
See #7
